### ISSUE TITLE
GitHub Action Integration Test Issue

### ISSUE THREAD

**Issue by mokagio** [mokagio/WordPress-iOS#1]
I'm working on integrating GitHub Actions, with the end goal of running all of the checks currently done with Peril with Actions + Danger, see https://github.com/wordpress-mobile/WordPress-iOS/issues/13366.

This issue will allow us to test the first integration experiment, annotating issues that don't have labels. The rule [lives here](https://github.com/Automattic/peril-settings/blob/7a7d11f69351d446b8e3a50d9e14a7fdf43a21e4/peril-settings.json#L17-19).

Expect a lot of label/un-label activity here 😄 .

**Comment by mokagio** [comment]
Creating this issue didn't result in a workflow execution. I'm not surprised, the code is not on ~~`master`~~ `develop` yet.

**Comment by mokagio** [comment]
Adding the label didn't trigger a workflow execution either. I was hoping it would because of the code is now in a PR, but I guess I need to merge it first.

Shame though, this will result in a lot of little merges on `develop`.

**Comment by mokagio** [comment]
Tried to remove the label with the PR no "Ready for review". Same result. Not surprising, but worth a shot.

**Comment by mokagio** [comment]
<img width="1680" alt="Screen Shot 2020-02-07 at 11 41 00" src="https://user-images.githubusercontent.com/1218433/73990928-bd6e3c00-499e-11ea-8fb7-a80ca31baf70.png">

Now we're talking 👍

**Comment by mokagio** [comment]
The [build kicked by adding this label](https://github.com/mokagio/WordPress-iOS/runs/430979851?check_suite_focus=true) failed with:

```
Unable to evaluate the Dangerfile
 TypeError: Cannot read property 'labels' of 
    at Object.<anonymous> (peril-downloaded-Automattic/peril-settings/org/issue/label.ts:96:48)
    at step (peril-downloaded-Automattic/peril-settings/org/issue/label.ts:76:27)
    at Object.next (peril-downloaded-Automattic/peril-settings/org/issue/label.ts:25:53)
    at peril-downloaded-Automattic/peril-settings/org/issue/label.ts:18:71
    at new Promise (<anonymous>)
    at __awaiter (peril-downloaded-Automattic/peril-settings/org/issue/label.ts:4:12)
    at Object.exports.default (peril-downloaded-Automattic/peril-settings/org/issue/label.ts:93:12)
    at Object.<anonymous> (/usr/src/danger/distribution/runner/runners/inline.js:147:60)
    at step (/usr/src/danger/distribution/runner/runners/inline.js:32:23)
    at Object.next (/usr/src/danger/distribution/runner/runners/inline.js:13:53)
```

"Cannot read property `'labels'` of..." 🤔 

I'm gonna remove the label to see what happens. I expect the build to fail again.

The fact that the `labels` property can't be read makes me wonder whether my token has the right access, or whether there's something that needs changing in the configuration.

Also... Why didn't the build fail for real? 🤔

**Comment by mokagio** [comment]
As expected, the [build kicked by removing the label](https://github.com/mokagio/WordPress-iOS/runs/430989008#step:3:28) failed as well.

There's a better formatted error in the log than the one I pasted above:

```
Cannot read property 'labels' of undefined
TypeError: Cannot read property 'labels' of undefined
    at Object.<anonymous> (peril-downloaded-Automattic/peril-settings/org/issue/label.ts:96:48)
    at step (peril-downloaded-Automattic/peril-settings/org/issue/label.ts:76:27)
    at Object.next (peril-downloaded-Automattic/peril-settings/org/issue/label.ts:25:53)
    at peril-downloaded-Automattic/peril-settings/org/issue/label.ts:18:71
    at new Promise (<anonymous>)
    at __awaiter (peril-downloaded-Automattic/peril-settings/org/issue/label.ts:4:12)
    at Object.exports.default (peril-downloaded-Automattic/peril-settings/org/issue/label.ts:93:12)
    at Object.<anonymous> (/usr/src/danger/distribution/runner/runners/inline.js:147:60)
    at step (/usr/src/danger/distribution/runner/runners/inline.js:32:23)
    at Object.next (/usr/src/danger/distribution/runner/runners/inline.js:13:53)
```

The only line accessing `labels` is [this](https://github.com/Automattic/peril-settings/blob/7a7d11f69351d446b8e3a50d9e14a7fdf43a21e4/org/issue/label.ts#L4)

```ts
const githubLabels = danger.github.issue.labels;
```

My TypeScript is very poor, but from what I gather I'd say `issue` is  what's `undefined`, otherwise the error would have been thrown earlier in the chaining.

This keeps pointing to my idea that the token doesn't have enough access. Maybe `issue` is `undefined` because it could not be read.

**Comment by mokagio** [comment]
The token has the [recommended scope](https://danger.systems/js/guides/getting_started.html#tokens-for-oss-projects) for a public repository:

<img width="952" alt="Screen Shot 2020-02-07 at 12 37 35" src="https://user-images.githubusercontent.com/1218433/73993905-c0b9f580-49a7-11ea-9c2f-1cba69e1bf5e.png">

<img width="946" alt="Screen Shot 2020-02-07 at 12 46 36" src="https://user-images.githubusercontent.com/1218433/73993955-e9da8600-49a7-11ea-9c67-be13b84708c7.png">


Moreover, I can't find any scope mentioning issues in [the GitHub docs](https://developer.github.com/apps/building-oauth-apps/understanding-scopes-for-oauth-apps/).

**Comment by mokagio** [comment]
I've been trying to get faster feedback by running Danger locally, but it can only run on PRs not issues. 

I might change the setup to run a rule for PRs, and go from there.

**Comment by mokagio** [comment]
I opened #23 with a proper setup. I'm going to add a label now to see if a workflow runs, but I doubt it will, we've seen already that the code needs to be on the base branch.

**Comment by mokagio** [comment]
No workflow triggered. 

I'm going to merge #23, then close this issue and open a new one to have a clean testing place.
